version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./data:/usr/share/elasticsearch/data